//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoloControl.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Kiosk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kiosk() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoloControl.Resources.Strings.Kiosk", typeof(Kiosk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pause exposition.
        /// </summary>
        internal static string Actions_Pause {
            get {
                return ResourceManager.GetString("Actions.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start exposition.
        /// </summary>
        internal static string Actions_Start {
            get {
                return ResourceManager.GetString("Actions.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stop and reset exposition.
        /// </summary>
        internal static string Actions_Stop {
            get {
                return ResourceManager.GetString("Actions.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show or hide output window.
        /// </summary>
        internal static string Actions_ToggleHistory {
            get {
                return ResourceManager.GetString("Actions.ToggleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Automatic Mode.
        /// </summary>
        internal static string Mode_Automatic {
            get {
                return ResourceManager.GetString("Mode.Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manual Mode.
        /// </summary>
        internal static string Mode_Manual {
            get {
                return ResourceManager.GetString("Mode.Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Blue Laser Time.
        /// </summary>
        internal static string Time_Blue {
            get {
                return ResourceManager.GetString("Time.Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný External Laser Time.
        /// </summary>
        internal static string Time_External {
            get {
                return ResourceManager.GetString("Time.External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finishing Time.
        /// </summary>
        internal static string Time_Finishing {
            get {
                return ResourceManager.GetString("Time.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Green Laser Time.
        /// </summary>
        internal static string Time_Green {
            get {
                return ResourceManager.GetString("Time.Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Red Laser Time.
        /// </summary>
        internal static string Time_Red {
            get {
                return ResourceManager.GetString("Time.Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Wait Time.
        /// </summary>
        internal static string Time_Waiting {
            get {
                return ResourceManager.GetString("Time.Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Blue Laser.
        /// </summary>
        internal static string Toggle_Blue {
            get {
                return ResourceManager.GetString("Toggle.Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný External Laser.
        /// </summary>
        internal static string Toggle_External {
            get {
                return ResourceManager.GetString("Toggle.External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finsihing LED.
        /// </summary>
        internal static string Toggle_Finishing {
            get {
                return ResourceManager.GetString("Toggle.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Green Laser.
        /// </summary>
        internal static string Toggle_Green {
            get {
                return ResourceManager.GetString("Toggle.Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Red Laser.
        /// </summary>
        internal static string Toggle_Red {
            get {
                return ResourceManager.GetString("Toggle.Red", resourceCulture);
            }
        }
    }
}
