//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoloControl.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Standard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Standard() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoloControl.Resources.Strings.Standard", typeof(Standard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kiosk Mode.
        /// </summary>
        internal static string Actions_Kiosk {
            get {
                return ResourceManager.GetString("Actions.Kiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Standard Mode.
        /// </summary>
        internal static string Actions_Standard {
            get {
                return ResourceManager.GetString("Actions.Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Clear output window.
        /// </summary>
        internal static string Console_Clear {
            get {
                return ResourceManager.GetString("Console.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Send.
        /// </summary>
        internal static string Console_Send {
            get {
                return ResourceManager.GetString("Console.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Console.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Get Colors.
        /// </summary>
        internal static string Controls_Information_Colors {
            get {
                return ResourceManager.GetString("Controls.Information.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Get Mode.
        /// </summary>
        internal static string Controls_Information_Mode {
            get {
                return ResourceManager.GetString("Controls.Information.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Get All Timings.
        /// </summary>
        internal static string Controls_Information_Times {
            get {
                return ResourceManager.GetString("Controls.Information.Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Information Controls.
        /// </summary>
        internal static string Controls_Information_Title {
            get {
                return ResourceManager.GetString("Controls.Information.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný no other options.
        /// </summary>
        internal static string Controls_Labels_NoOptions {
            get {
                return ResourceManager.GetString("Controls.Labels.NoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný B.
        /// </summary>
        internal static string Controls_Manual_Color_B {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ext.
        /// </summary>
        internal static string Controls_Manual_Color_Ext {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finishing.
        /// </summary>
        internal static string Controls_Manual_Color_Finishing {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný G.
        /// </summary>
        internal static string Controls_Manual_Color_G {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný R.
        /// </summary>
        internal static string Controls_Manual_Color_R {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set Colors.
        /// </summary>
        internal static string Controls_Manual_Colors {
            get {
                return ResourceManager.GetString("Controls.Manual.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Toggle External.
        /// </summary>
        internal static string Controls_Manual_External {
            get {
                return ResourceManager.GetString("Controls.Manual.External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Toggle Finishing.
        /// </summary>
        internal static string Controls_Manual_Finishing {
            get {
                return ResourceManager.GetString("Controls.Manual.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manual Controls.
        /// </summary>
        internal static string Controls_Manual_Title {
            get {
                return ResourceManager.GetString("Controls.Manual.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pause.
        /// </summary>
        internal static string Controls_Run_Pause {
            get {
                return ResourceManager.GetString("Controls.Run.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start.
        /// </summary>
        internal static string Controls_Run_Start {
            get {
                return ResourceManager.GetString("Controls.Run.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stop.
        /// </summary>
        internal static string Controls_Run_Stop {
            get {
                return ResourceManager.GetString("Controls.Run.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Run Controls.
        /// </summary>
        internal static string Controls_Run_Title {
            get {
                return ResourceManager.GetString("Controls.Run.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set Blue Timing.
        /// </summary>
        internal static string Controls_Timing_Blue {
            get {
                return ResourceManager.GetString("Controls.Timing.Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set External Timing.
        /// </summary>
        internal static string Controls_Timing_External {
            get {
                return ResourceManager.GetString("Controls.Timing.External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set Finishing Time.
        /// </summary>
        internal static string Controls_Timing_Finishing {
            get {
                return ResourceManager.GetString("Controls.Timing.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set Green Timing.
        /// </summary>
        internal static string Controls_Timing_Green {
            get {
                return ResourceManager.GetString("Controls.Timing.Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set Red Timing.
        /// </summary>
        internal static string Controls_Timing_Red {
            get {
                return ResourceManager.GetString("Controls.Timing.Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reset All Timings.
        /// </summary>
        internal static string Controls_Timing_Reset {
            get {
                return ResourceManager.GetString("Controls.Timing.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exposition Time:.
        /// </summary>
        internal static string Controls_Timing_Time {
            get {
                return ResourceManager.GetString("Controls.Timing.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Timing Controls.
        /// </summary>
        internal static string Controls_Timing_Title {
            get {
                return ResourceManager.GetString("Controls.Timing.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set Wait Time.
        /// </summary>
        internal static string Controls_Timing_Wait {
            get {
                return ResourceManager.GetString("Controls.Timing.Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connect.
        /// </summary>
        internal static string Port_Connect {
            get {
                return ResourceManager.GetString("Port.Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connected.
        /// </summary>
        internal static string Port_Status_Connected {
            get {
                return ResourceManager.GetString("Port.Status.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Connecting....
        /// </summary>
        internal static string Port_Status_Connecting {
            get {
                return ResourceManager.GetString("Port.Status.Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Disconnected.
        /// </summary>
        internal static string Port_Status_Disconnected {
            get {
                return ResourceManager.GetString("Port.Status.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error.
        /// </summary>
        internal static string Port_Status_Error {
            get {
                return ResourceManager.GetString("Port.Status.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Status:.
        /// </summary>
        internal static string Port_Status_Title {
            get {
                return ResourceManager.GetString("Port.Status.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Port.
        /// </summary>
        internal static string Port_Title {
            get {
                return ResourceManager.GetString("Port.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný s.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
    }
}
