//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoloControl.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Standard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Standard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoloControl.Resources.Strings.Standard", typeof(Standard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Console_Send {
            get {
                return ResourceManager.GetString("Console.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Colors.
        /// </summary>
        internal static string Controls_Information_Colors {
            get {
                return ResourceManager.GetString("Controls.Information.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Mode.
        /// </summary>
        internal static string Controls_Information_Mode {
            get {
                return ResourceManager.GetString("Controls.Information.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Timings.
        /// </summary>
        internal static string Controls_Information_Times {
            get {
                return ResourceManager.GetString("Controls.Information.Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Controls.
        /// </summary>
        internal static string Controls_Information_Title {
            get {
                return ResourceManager.GetString("Controls.Information.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no other options.
        /// </summary>
        internal static string Controls_Labels_NoOptions {
            get {
                return ResourceManager.GetString("Controls.Labels.NoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Controls_Manual_Color_B {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        internal static string Controls_Manual_Color_Ext {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        internal static string Controls_Manual_Color_Finishing {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string Controls_Manual_Color_G {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Controls_Manual_Color_R {
            get {
                return ResourceManager.GetString("Controls.Manual.Color.R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Colors.
        /// </summary>
        internal static string Controls_Manual_Colors {
            get {
                return ResourceManager.GetString("Controls.Manual.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle External.
        /// </summary>
        internal static string Controls_Manual_External {
            get {
                return ResourceManager.GetString("Controls.Manual.External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Finishing.
        /// </summary>
        internal static string Controls_Manual_Finishing {
            get {
                return ResourceManager.GetString("Controls.Manual.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Controls.
        /// </summary>
        internal static string Controls_Manual_Title {
            get {
                return ResourceManager.GetString("Controls.Manual.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Controls_Run_Pause {
            get {
                return ResourceManager.GetString("Controls.Run.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Controls_Run_Start {
            get {
                return ResourceManager.GetString("Controls.Run.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Controls_Run_Stop {
            get {
                return ResourceManager.GetString("Controls.Run.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Controls.
        /// </summary>
        internal static string Controls_Run_Title {
            get {
                return ResourceManager.GetString("Controls.Run.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Blue Timing.
        /// </summary>
        internal static string Controls_Timing_Blue {
            get {
                return ResourceManager.GetString("Controls.Timing.Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set External Timing.
        /// </summary>
        internal static string Controls_Timing_External {
            get {
                return ResourceManager.GetString("Controls.Timing.External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Finishing Time.
        /// </summary>
        internal static string Controls_Timing_Finishing {
            get {
                return ResourceManager.GetString("Controls.Timing.Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Green Timing.
        /// </summary>
        internal static string Controls_Timing_Green {
            get {
                return ResourceManager.GetString("Controls.Timing.Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Red Timing.
        /// </summary>
        internal static string Controls_Timing_Red {
            get {
                return ResourceManager.GetString("Controls.Timing.Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Timings.
        /// </summary>
        internal static string Controls_Timing_Reset {
            get {
                return ResourceManager.GetString("Controls.Timing.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposision Time:.
        /// </summary>
        internal static string Controls_Timing_Time {
            get {
                return ResourceManager.GetString("Controls.Timing.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing Controls.
        /// </summary>
        internal static string Controls_Timing_Title {
            get {
                return ResourceManager.GetString("Controls.Timing.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Wait Time.
        /// </summary>
        internal static string Controls_Timing_Wait {
            get {
                return ResourceManager.GetString("Controls.Timing.Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Port_Connect {
            get {
                return ResourceManager.GetString("Port.Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Port_Status_Connected {
            get {
                return ResourceManager.GetString("Port.Status.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Port_Status_Connecting {
            get {
                return ResourceManager.GetString("Port.Status.Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Port_Status_Disconnected {
            get {
                return ResourceManager.GetString("Port.Status.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Port_Status_Error {
            get {
                return ResourceManager.GetString("Port.Status.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Port_Status_Title {
            get {
                return ResourceManager.GetString("Port.Status.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port_Title {
            get {
                return ResourceManager.GetString("Port.Title", resourceCulture);
            }
        }
    }
}
